_commit: v1.12.1-10-g6796849
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: daemonsets.yaml
backups: false
helm: false
homepageEnabled: false
ingress: false
labels: 'app: prometheus'
name: prometheus
namespace: prometheus
pvc: false
reloader: true
resources:
- configmaps.yaml
- deployments.yaml
- pvcs.yaml
- rbac.yaml
- service-accounts.yaml
- services.yaml
- statefulsets.yaml
service: false
serviceAccount: false
upstreamURL: https://prometheus.io/
url: https://github.com/charlesthomas/homelab-prometheus
