---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-prometheus
commonLabels:
  app: prometheus

resources:
- resources/configmaps.yaml
- resources/daemonsets.yaml
- resources/deployments.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/rbac.yaml
- resources/service-accounts.yaml
- resources/services.yaml
- resources/statefulsets.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: prometheus
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
- patch: |-
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: all
      namespace: prometheus
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: StatefulSet
